name: Build Project ⚙️

on: 
  push: { branches: ["master"] }

env:
  # License
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildForWindows:
    name: "Build for windows"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-macos-${{ matrix.targetPlatform }}
          restore-keys: | 
            Library-macos-
            Library-
      - uses: game-ci/unity-builder@v2.1.0
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: Build MacOS (${{ matrix.targetPlatform }})
          path: build
